development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: newpoint_dev
  pool:     5
  username: chenxi
  password:

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: newpoint_test
  pool:     5
  username: chenxi
  password:

production:
  adapter:  postgresql
  host:
  encoding: unicode
  database: myapp_production
  pool:     5
  username:
  password:

